
function getComputerChoice() {
    /*generating a random number between 0 and 2 */
    let random = () => {
    return Math.floor(Math.random() * 3)
    }
    
    /* switch statement to assign rock, paper and scissors strings depending on the random number generated by random()*/
    switch(random()) {
        case 0: 
            return 'Rock'
        case 1:
            return 'Paper'
        case 2:
            return 'Scissors'
    }
}

function playRound (playerSelection, computerSelection) {
    if(playerSelection === computerSelection) { 
        return "This is a tie" 
    } else if (playerSelection === 'rock' && computerSelection === 'scissors') {
        return 'You win! Rock beats Scissors'
    } else if (playerSelection === 'paper' && computerSelection === 'rock') {
        return 'You win! Paper beats Rock'
    } else if (playerSelection === 'scissors' && computerSelection === 'paper') {
        return 'You win! Scissors beats Paper'
    } else {
        return "You Lose! " + computerSelection + " beats " + playerSelection
    }
}
    
let computerSelection = getComputerChoice().toLowerCase()
let playerSelection = 'Rock'.toLowerCase()

console.log(playRound(playerSelection, computerSelection))