let wins = 0
let looses = 0
let count = 0


//This is the logic for the DOM management

const container = document.querySelector('#container')
const results = document.querySelector('#results')

const button1 = document.createElement('button')
const button2 = document.createElement('button')
const button3 = document.createElement('button')
const totalCount = document.createElement('p')
const winner = document.createElement('p')
const end = document.createElement('p')
const announce = document.createElement('p')

button1.classList.add('button')
button1.setAttribute('id', 'rock')
button1.textContent = 'Rock'
container.appendChild(button1)

button2.classList.add('button')
button2.setAttribute('id', 'paper')
button2.textContent = 'Paper'
container.appendChild(button2)

button3.classList.add('button')
button3.setAttribute('id', 'scissors')
button3.textContent = 'Scissors'
container.appendChild(button3)

const buttons = container.querySelectorAll('button')

const rock = document.querySelector(`button[id="rock"]`)
const paper = document.querySelector(`button[id="paper"]`)
const scissors = document.querySelector(`button[id="scissors"]`)

buttons.forEach((button) => {
    button.addEventListener('click', (e) => {
        if(e.target == rock) playRound('rock')
        if(e.target == paper) playRound('paper')
        if(e.target == scissors) playRound('scissors')
    })
})
totalCount.textContent = `Wins: ${wins} Looses: ${looses}`
totalCount.setAttribute('id', 'count')

winner.setAttribute('id', 'winner')

end.setAttribute('id', 'end')

announce.setAttribute('id', 'announce')

results.appendChild(announce)
results.appendChild(totalCount)
results.appendChild(end)
results.appendChild(winner)



//-------------------------------------Web logic below this line-------------------------------------------------------------------------

function getComputerChoice() {
    /*generating a random number between 0 and 2 */
    let random = () => {
    return Math.floor(Math.random() * 3)
    }
    
    /* switch statement to assign rock, paper and scissors strings depending on the random number generated by random()*/
    switch(random()) {
        case 0: 
            return 'Rock'
        case 1:
            return 'Paper'
        case 2:
            return 'Scissors'
    }
}

/* function with the logic to play one round of rock paper and scissors */
function playRound(playerSelection) {
    let computerSelection = getComputerChoice().toLowerCase()


    while(count < 5) {
        if(playerSelection === computerSelection) { 
            count++
            return document.getElementById('announce').innerHTML = 'This is a tie'
        } else if (playerSelection === 'rock' && computerSelection === 'scissors') {
            wins++
            count++
            document.getElementById('count').innerHTML = `Wins: ${wins} Looses: ${looses}`
            return document.getElementById('announce').innerHTML = `You win! ${playerSelection} beats ${computerSelection}`
        } else if (playerSelection === 'paper' && computerSelection === 'rock') {
            wins++
            count++
            document.getElementById('count').innerHTML = `Wins: ${wins} Looses: ${looses}`
            return document.getElementById('announce').innerHTML = `You win! ${playerSelection} beats ${computerSelection}`
        } else if (playerSelection === 'scissors' && computerSelection === 'paper') {
            wins++
            count++
            document.getElementById('count').innerHTML = `Wins: ${wins} Looses: ${looses}`
            return document.getElementById('announce').innerHTML = `You win! ${playerSelection} beats ${computerSelection}`
        } else {
            count++
            looses++
            document.getElementById('count').innerHTML = `Wins: ${wins} Looses: ${looses}`
            return document.getElementById('announce').innerHTML = `You loose! ${computerSelection} beats ${playerSelection}`
        }
    }
    endGame()
}

/*function to play the game 5 times and added a conditional to add a message when the game ends (fifth round) and a message to announce who wins */


function endGame() {
    if(count === 5) {
        document.getElementById('end').innerHTML = `GAME ENDS`
    }

    if(wins === looses){
        document.getElementById('winner').innerHTML = `DRAW!!!`
    } else if(wins > looses) {
        document.getElementById('winner').innerHTML = `Player WINS!!!`
    } else {
        document.getElementById('winner').innerHTML = `Computer WINS!!!`
    }
    
}


